2_框架/2_Django框架/2_模型视图/pytest/test1/booktest/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[

    url(r'^$',views.index),
    url(r'^delete(\d+)/$',views.delete),
    url(r'^create/$',views.create),
]

2_框架/2_Django框架/2_模型视图/pytest/test1/course/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[

    url(r'^set_cookie/$',views.set_cookie),
    url(r'^get_cookie/$',views.get_cookie),

    url(r'^set_session/$',views.set_session),
    url(r'^get_session/$',views.get_session),

    url(r'^json1/$', views.json1),
    url(r'^json2/$', views.json2),

    # url(r'^\d+/$',views.show1),
    url(r'^(\d+)/$',views.show1),
    url(r'^(?P<id1>\d+)/$',views.show1),

    url(r'^method1/$', views.method1),
    url(r'^method2/$', views.method2),
    url(r'^method3/$', views.method3),

    url(r'^get1/$',views.get1),
    url(r'^get2/$',views.get2),
    url(r'^get3/$',views.get3),


    url(r'^post1/$',views.post1),
    url(r'^post2/$',views.post2),

    url(r'^fan1/$', views.fan1),

    url(r'^fan2/$', views.fan2),
    url(r'^fan_show/$', views.fan2,name='fan3'),
]

2_框架/2_Django框架/2_模型视图/pytest/test1/test1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    #引入booktest的url配置
    url(r'^',include('booktest.urls')),
    url(r'^',include('course.urls')),
    url(r'^', include('course.urls', namespace='course')),
]

2_框架/2_Django框架/2_模型视图/pytest/test1/booktest/models.py
#coding=utf-8
from django.db import models



#定义图书模型类BookInfo
class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)#图书名称
    bpub_date = models.DateField()#发布日期
    bread = models.IntegerField(default=0)#阅读量
    bcommet = models.IntegerField(default=0)#评论量
    isDelete = models.BooleanField(default=False)#逻辑删除
    class Meta:#元信息类
        db_table='bookinfo'#指定表的名称

#定义英雄模型类HeroInfo
class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)#英雄姓名
    hgender = models.BooleanField(default=True)#英雄性别
    isDelete = models.BooleanField(default=False)#逻辑删除
    hcontent = models.CharField(max_length=100)#英雄描述信息
    hbook = models.ForeignKey('BookInfo')#英雄与图书表的关系为一对多，所以属性定义在英雄模型中

2_框架/2_Django框架/2_模型视图/pytest/test1/booktest/views.py
#coding=utf-8
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import BookInfo,HeroInfo
from datetime import date
from django.db.models import F,Q
from django.db.models import Sum
#查询所有图书并显示


def index(request):

    # list = BookInfo.objects.all()
    # return render(request, 'booktest/index.html', {'list': list})

    #1 限制查询集
    # list=BookInfo.objects.all()[0:2]
    # return render(request, 'booktest/index.html', {'list': list})

    #2 exact：表示判等
    # list=BookInfo.objects.filter(id__exact=4)
    # 简写
    # list = BookInfo.objects.filter(id=1)
    # return render(request, 'booktest/index.html', {'list': list})



    #基本查询

    # 3 contains：是否包含
    # 查询书名包含‘传’的图书
    # list=BookInfo.objects.filter(btitle__contains='传')
    # return render(request, 'booktest/index.html', {'list': list})

    #4 startswith、endswith：以指定值开头或结尾
    # 查询书名以‘部’结尾的图书
    # list=BookInfo.objects.filter(btitle__endswith='部')
    # return render(request, 'booktest/index.html', {'list': list})

    #5 isnull：是否为null
    # 查询书名不为空的图书
    # list=BookInfo.objects.filter(btitle__isnull=False)
    # return render(request,'booktest/index.html',{'list':list})

    #6  in ：是否包含在范围内
    # 查询编号为1或3或5的图书
    # list=BookInfo.objects.filter(pk__in=[1,3])
    # return render(request,'booktest/index.html',{'list':list})

    #7 gt、gte、lt、lte：大于、大于等于、小于、小于等于
    # 查询编号大于3的图书
    # list=BookInfo.objects.filter(id__gt=3)
    # return render(request,'booktest/index.html',{'list':list})

    #8 不等于使用等于的运算符，使用exclude()过滤器
    # 例：查询编号不等于3的图书
    # list=BookInfo.objects.exclude(id=3)
    # return render(request,'booktest/index.html',{'list':list})

    #9 year、month、day、week_day、hour、minute、second：对日期时间类型的属性进行运算
    # 查询1980年发表的图书
    # list=BookInfo.objects.filter(bpub_date__year=1980)
    # return render(request,'booktest/index.html',{'list':list})

    #10 查询1980年1月1日后发表的图书
    # list=BookInfo.objects.filter(bpub_date__gt=date(1980,5,1))
    # return render(request,'booktest/index.html',{'list':list})

    #11 F对象 两个对象之间的比较
    # 查询阅读量大于等于评论量的图书
    # list=BookInfo.objects.filter(bread__gt=F('bcommet'))
    # return render(request,'booktest/index.html',{'list':list})

    # 查询阅读量大于2倍评论量的图书
    # list = BookInfo.objects.filter(bread__gt=F('bcommet')*2)
    # return render(request, 'booktest/index.html', {'list': list})

    # 11逻辑关系（Q对象可以使用&、|连接，&表示逻辑与，|表示逻辑或）
    # 逻辑与  ，
    # 查询阅读量大于20，并且编号小于3的图书
    # list=BookInfo.objects.filter(bcommet__gt=20,id__lt=3)
    # list=BookInfo.objects.filter(Q(bread__gt=20) & Q(id__lt=3))

    # return render(request, 'booktest/index.html', {'list': list})

    # Q(属性名__运算符=值)
    # 逻辑或
    # 查询阅读量大于20，或编号小于3的图书

    # list = BookInfo.objects.filter(Q(bread__gt=20) | Q(pk__lt=3))
    return render(request, 'booktest/index.html', {'list': list})

    # 逻辑非
    # 查询编号不等于3的图书
    # list=BookInfo.objects.filter(~Q(id=3))

    #第二种方法
    # list=BookInfo.objects.exclude(id=2)
    # return render(request, 'booktest/index.html', {'list': list})



    # 关联查询
    # 关联模型类名小写__属性名__运算符 = 值
    # 查询图书，要求图书中英雄的描述包含‘八’

    # list=BookInfo.objects.filter(heroinfo__hcontent__contains='六')
    # return render(request, 'booktest/index.html', {'list': list})

    # heros=HeroInfo.objects.get(hcontent='降龙十八掌')[0,1]
    # list=heros.hbook()
    # return render(request, 'booktest/index.html', {'list': list})


    # 查询书名为“天龙八部”的所有英雄
    # list=HeroInfo.objects.filter(hbook__btitle='天龙八部')
    # return render(request, 'booktest/index.html', {'list': list})


    # 聚合函数
    # 使用aggregate()过滤器调用聚合函数
    # 聚合函数包括：Avg，Count，Max，Min，Sum，被定义在django.db.models中
    # 例：查询图书的总阅读量
    # list = BookInfo.objects.aggregate(Sum('bread'))
    # print(list)
    # return HttpResponse(list['bread__sum'])

    # 查询图书总数
    # list=BookInfo.objects.count()
    # print(list)
    # return HttpResponse(list)

    # 关联的查询
    # 查询编号为1的图书
    # book=BookInfo.objects.get(id=1)
    # 获得book图书的所有英雄(一找多)
    # heros=book.heroinfo_set.all()
    # print(heros)
    # return HttpResponse(heros)


    # 获得编号为1的英雄
    # hero = HeroInfo.objects.get(id=1)
    # # 查询英雄对应的书(多找一)
    # book = hero.hbook
    # print(book.btitle)
    # return HttpResponse(book)

#创建新图书
def create(request):
    # book=BookInfo.objects.create('流星蝴蝶剑')
    book = BookInfo.objects.create('流星蝴蝶剑', date(1995,12,30))
    book.save()
    #转向到首页
    return redirect('/')

#逻辑删除指定编号的图书
def delete(request,id):
    print(id)
    book=BookInfo.objects.get(pk=int(id))
    book.isDelete=True
    book.save()
    #转向到首页
    return redirect('/')

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/fan1.html
<html>
<head>
    <title>反向解析</title>
</head>
<body>
普通链接：<a href="/fan2/">fan2</a>
<hr>
反向解析：<a href="{%url 'course:fan3'%}">fan2</a>
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/fan12.html
<html>
<head>
    <title>反向解析</title>
</head>
<body>
普通链接：<a href="/fan2/">fan2</a>
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/get1.html
<html>
<head>
    <title>GET属性</title>
</head>
<body>
链接1：一个键传递一个值<br>
<a href="/get2/?a=1&b=2">get2</a>
<hr>
链接2：一个键传递多个值<br>
<a href="/get3/?a=1&a=2&b=3">get3</a>
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/get2.html
<html>
<head>
    <title>GET属性一键一值</title>
</head>
<body>
a:{{a}}
<hr>
b:{{b}}
<hr>
c:{{c}}
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/get3.html
<html>
<head>
    <title>GET属性一键多值</title>
</head>
<body>
a:
<ul>
    {%for i in a%}
    <li>{{i}}</li>
    {%endfor%}
</ul>
<hr>
b:{{b}}
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/index.html
<html>
<head>
    <title>Title</title>
</head>
<body>
<a href="/create/">创建</a>
<ul>
{%for book in list%}
<li>{{book.btitle}}--<a href="/delete{{book.id}}/">删除</a></li>
{%endfor%}
{#{%for book in list%}#}
{#    <li>{{book.btitle}}--<a href="/delete{{book.id}}/">删除</a></li>#}
{#    <li>{{ book.btitle }}</li>#}
{#{%endfor%}#}
{#{%for hero in list%}#}
{#    <li>{{book.btitle}}--<a href="/delete{{book.id}}/">删除</a></li>#}
{#    <li>{{ hero.hname }}</li>#}
{#{%endfor%}#}
</ul>
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/json1.html
<html>
<head>
    <title>json</title>
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script>
{#        $(function () {#}
{#            $('#btnJson').click(function () {#}
{#                $.get('/json2/',function (data) {#}
{#                    ul=$('#jsonList');#}
{#                    ul.append('<li>'+data['h1']+'</li>')#}
{#                    ul.append('<li>'+data['h2']+'</li>')#}
{#                })#}
{#            });#}
{#        });#}

        $(function(){
            $('#btnJson').click(function() {
               $.get('/json2/',function(data){
                   ul=$('#jsonList');
                   ul.append('<li>'+data['h1']+'</li>')
                   ul.append('<li>'+data['h2']+'</li>')
               })
            })
        })
    </script>
</head>
<body>
<input type="button" id="btnJson" value="获取json数据">
<ul id="jsonList"></ul>
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/method1.html
<html>
<head>
    <title>方法练习</title>
</head>
<body>
<a href="/method2/">方式一：get</a>
<br>
<br>
<br>
<form method="post" action="/method3/">
    <input type="submit" value="方式二：post">
</form>
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/post1.html
<html>
<head>
    <title>POST属性</title>
</head>
<body>
<form method="post" action="/post2/">
    姓名：<input type="text" name="uname"/><br>
    密码：<input type="password" name="upwd"/><br>
    性别：<input type="radio" name="ugender" value="1"/>男
    <input type="radio" name="ugender" value="0"/>女<br>
    爱好：<input type="checkbox" name="uhobby" value="胸口碎大石"/>胸口碎大石
    <input type="checkbox" name="uhobby" value="脚踩电灯炮"/>脚踩电灯炮
    <input type="checkbox" name="uhobby" value="口吐火"/>口吐火<br>
    <input type="submit" value="提交"/>
</form>
</body>
</html>

2_框架/2_Django框架/2_模型视图/pytest/test1/templates/booktest/post2.html
<html>
<head>
    <title>POST属性</title>
</head>
<body>
用户名：{{uname}}<br>
密码：{{upwd}}<br>
性别：{{ugender}}<br>
爱好：{{uhobby}}<br>
<ul>
    {%for i in uhobby%}
    <li>{{i}}</li>
    {%endfor%}
</ul>
</body>
</html>