2_框架/2_Django框架/1_入门/test1/booktest/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^index1$', views.index1),
    url(r'^index2$', views.index2),
    url(r'^index$', views.index3),
    url(r'^(\d+)$', views.detail),
]

2_框架/2_Django框架/1_入门/test1/test1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('booktest.urls')),
]

2_框架/2_Django框架/1_入门/test1/booktest/models.py
from django.db import models

class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateField()
    def __str__(self):
        return "%d" % self.pk

class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=100)
    hBook = models.ForeignKey('BookInfo')
    def __str__(self):
        return "%d" % self.pk

2_框架/2_Django框架/1_入门/test1/booktest/views.py
#coding:utf-8

from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader,RequestContext

from booktest.models import BookInfo


def index(request):
    return HttpResponse("index")

def index1(request):
    # 1.获取模板
    template=loader.get_template('booktest/index.html')
    # 2.定义上下文
    context=RequestContext(request,{'title':'图书列表','list':range(10)})
    # 3.渲染模板
    return HttpResponse(template.render(context))

def index2(request):
    context={'title':'图书列表','list':range(5)}
    return render(request,'booktest/index.html',context)


#首页，展示所有图书
def index3(reqeust):
    #查询所有图书
    booklist = BookInfo.objects.all()
    #将图书列表传递到模板中，然后渲染模板
    return render(reqeust, 'booktest/index.html', {'booklist': booklist})

#详细页，接收图书的编号，根据编号查询，再通过关系找到本图书的所有英雄并展示
def detail(reqeust, id):
    #根据图书编号对应图书
    book = BookInfo.objects.get(pk=id)
    #将图书信息传递到模板中，然后渲染模板
    return render(reqeust, 'booktest/detail.html', {'book': book})

2_框架/2_Django框架/1_入门/test1/templates/booktest/detail.html
<html>
<head>
    <title>详细页</title>
</head>
<body>
{#输出图书标题#}
<h1>{{book.btitle}}</h1>
<ul>
    {#通过关系找到本图书的所有英雄，并遍历#}
    {%for hero in book.heroinfo_set.all%}
    {#输出英雄的姓名及描述#}
    <li>{{hero.hname}}---{{hero.hcontent}}</li>
    {%endfor%}
</ul>
</body>
</html>

2_框架/2_Django框架/1_入门/test1/templates/booktest/index.html
<html>
<head>
    <title>图书列表</title>
</head>
<body>
<h1>{{title}}</h1>
{#{%for i in list%}#}
{#{{i}}<br>#}
{#{%endfor%}#}
{%for book in booklist%}
   <li>
     {#输出图书名称，并设置超链接，链接地址是一个数字#}
      <a href="{{book.id}}">{{book.btitle}}</a>
    </li>
{%endfor%}
</body>
</html>